services:
  bankaccounts.db:
    image: lithiumkgp/postgres:latest
    container_name: bankaccounts_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bank-accounts-db
    volumes:
      - bankaccounts_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  bankaccounts.api:
    image: lithiumkgp/bankaccounts.api:latest
    build:
      context: .
      dockerfile: BankAccounts.Api/Dockerfile
    ports:
      - "80:80" 
    depends_on:
      bankaccounts.db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  bankaccounts.identity:
    image: lithiumkgp/bankaccounts.identity:latest
    build:
      context: .
      dockerfile: BankAccounts.Identity/Dockerfile
    ports:
      - "7045:7045"

  rabbitmq:
    image: lithiumkgp/rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    restart: unless-stopped
    healthcheck:
        test: [ "CMD-SHELL", "rabbitmq-diagnostics -q check_virtual_hosts" ]
        interval: 5s
        timeout: 5s
        retries: 5
        start_period: 5s

volumes:
  bankaccounts_db_data:
  rabbitmq_data: