services:
  bankaccounts.api:
    image: lithiumkgp/bankaccounts.api:latest
    build:
      context: .
      dockerfile: BankAccounts.Api/Dockerfile
    ports:
      - "80:80" 
      - "81:81" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:81
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev-password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./aspnetapp.pfx
  bankaccounts.identity:
    image: lithiumkgp/bankaccounts.identity:latest
    build:
      context: .
      dockerfile: BankAccounts.Identity/Dockerfile
    ports:
      - "7044:7044"
      - "7045:7045"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7044
      - ASPNETCORE_Kestrel__Certificates__Default__Password=dev-password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./aspnetapp.pfx