services:
  bankaccounts.api:
    image: lithiumkgp/bankaccounts.api:latest
    build:
      context: .
      dockerfile: BankAccounts.Api/Dockerfile
    ports:
      - "80:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
      - ASPNETCORE_URLS=http://+:80
  bankaccounts.identity:
    image: lithiumkgp/bankaccounts.identity:latest
    build:
      context: .
      dockerfile: BankAccounts.Identity/Dockerfile
    ports:
      - "7045:7045"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=7045
      - ASPNETCORE_URLS=http://+:7045