@adress = https://localhost:80
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlOTNhZmJjYy00YzhkLTRkZDYtYmY5Ni1hNmE4ZTFjZjM3ZmYiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZG1pdHJpeV9rb3Bvc292IiwiZXhwIjoxNzU0MDY1ODg5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4MCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjgwIn0.omfVy1CHIknnP9mN5jaiaR5_SBweeua01683sUn_eMs
POST {{adress}}/api/Accounts
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ownerId": "32fa6b5e-8b1a-4c2a-9f4b-7c8d1e2f3a4b",
    "accountType": "Credit",
    "currency": "rub"
}

### Create account
POST {{adress}}/api/Accounts
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ownerId": "32fa6b5e-8b1a-4c2a-9f4b-7c8d1e2f3a4b",
    "accountType": "Deposit",
    "currency": "eur"
}

### Get all user acounts
GET {{adress}}/api/accounts/all
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ownerId": "32fa6b5e-8b1a-4c2a-9f4b-7c8d1e2f3a4b"
}

### Get account
GET {{adress}}/api/accounts/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ownerId": "32fa6b5e-8b1a-4c2a-9f4b-7c8d1e2f3a4b"
}

### Delete account
DELETE {{adress}}/api/accounts/2
Authorization: Bearer {{token}}

### Patch account
PATCH {{adress}}/api/accounts/2?interestRate=10.00&close=true
Authorization: Bearer {{token}}

### Perform transaction
POST {{adress}}/api/accounts/transactions
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "accountId": 1,
    "transactionType": "Debit",
    "amount": 100.00,
    "description" : "New transaction"
}

### Get all transaction for account
GET {{adress}}/api/accounts/2/transactions/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "fromDate": "2025-07-30",
  "toDate": "2025-08-20"
}

### Get transaction by Guid
GET {{adress}}/api/accounts/transactions/4f2feff3-0055-4a28-bd63-4162826219aa
Authorization: Bearer {{token}}

### Perform transfer
POST {{adress}}/api/accounts/transfer
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "fromAccountId": 1,
    "toAccountId": 2,
    "amount": 100.00
}