@adress = https://localhost:80
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyZjQ2ODU3Zi1kZjJkLTQwM2EtYmE2OS03ODNmN2NjYmJmYTAiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZG1pdHJpeV9rb3Bvc292MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZjVjMWRlMzctYmEwYy00MmEwLWFiMTItYTI2Y2E2M2I2OTZkIiwiZXhwIjoxNzU0MTQwOTc5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo4MCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjgwIn0.l7CtyMnRwPN6LHgIfZYNcK9_87rDf_eYk2oCVN-4ZU0

### Create account 1
POST {{adress}}/api/Accounts
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "accountType": "Checking",
    "currency": "rub",
    "interestRate": 0.00
}

### Create account 2
POST {{adress}}/api/Accounts
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "accountType": "Deposit",
    "currency": "eur"
}

### Get all user accounts
GET {{adress}}/api/accounts/all
Authorization: Bearer {{token}}

### Get account 1
GET {{adress}}/api/accounts/1
Authorization: Bearer {{token}}

### Delete account 1
DELETE {{adress}}/api/accounts/1
Authorization: Bearer {{token}}

### Patch account 1
PATCH {{adress}}/api/accounts/1?interestRate=10.00&close=true
Authorization: Bearer {{token}}

### Perform transaction +100 rub to account 1
POST {{adress}}/api/accounts/transactions
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "accountId": 1,
    "transactionType": "Debit",
    "amount": 100.00,
    "description" : "New transaction"
}

### Get all transaction for account 1
GET {{adress}}/api/accounts/1/transactions?fromDate=2025-07-30&toDate=2025-08-20
Authorization: Bearer {{token}}

### Get transaction by Guid
GET {{adress}}/api/accounts/transactions/bcfc6245-5c18-473e-a12a-f3d390722790
Authorization: Bearer {{token}}

### Perform transfer from account 1 to 2 100 rub
POST {{adress}}/api/accounts/transfer
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "fromAccountId": 1,
    "toAccountId": 2,
    "amount": 100.00
}